// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd0TNw899hFwd5vgrA--VDozwKApduO1c',
    appId: '1:382734556035:web:38a8c7d6e7998646dbf4b6',
    messagingSenderId: '382734556035',
    projectId: 'mynotes-1681c',
    authDomain: 'mynotes-1681c.firebaseapp.com',
    storageBucket: 'mynotes-1681c.appspot.com',
    measurementId: 'G-RF9QQKPGJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeieHmuMJAZ6d-Scdmhz8nU2nycGnZz2A',
    appId: '1:382734556035:android:7dbac7b77eaad7e3dbf4b6',
    messagingSenderId: '382734556035',
    projectId: 'mynotes-1681c',
    storageBucket: 'mynotes-1681c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3FW9VInv2eXby4aT2bIWCEMod4ONwpC8',
    appId: '1:382734556035:ios:96619d6435364790dbf4b6',
    messagingSenderId: '382734556035',
    projectId: 'mynotes-1681c',
    storageBucket: 'mynotes-1681c.appspot.com',
    iosClientId: '382734556035-76j02cdc0tc5ns2mvevc05oq4gt38eku.apps.googleusercontent.com',
    iosBundleId: 'mynotes',
  );
}
